First release
scilus/register_flow pull request #1
Opened 2022-03-06 15:58 UTC by arnaudbore

2022-03-10 21:37 UTC, CHrlS98 reviewed
I tried with the default parameters and the optional ones after running `combine_flows` on a `tractoflow` output.
Works really well. Only thing I noticed is that the registered nufo has floating point values. Is this expected?

2022-03-10 21:37 UTC, CHrlS98 commented on USAGE
> +toTemplate_flow pipeline
`toTemplate_flow` or `register_flow`?

2022-03-10 21:37 UTC, CHrlS98 commented on USAGE
> +AVAILABLE PROFILES (using -profile option (e.g. -profile use_cuda,fully_reproducible))
Is `use_cuda` an available profile ? I get that it is an example but maybe we should put an available profile for example?

2022-03-10 21:37 UTC, CHrlS98 commented on USAGE
> +AVAILABLE PROFILES (using -profile option (e.g. -profile use_cuda,fully_reproducible))
Is `use_cuda` an available profile ? I get that it is an example but maybe we should put an available profile for example?

2022-03-10 21:37 UTC, CHrlS98 commented on USAGE
> +    --template                                  Template used for registration.
I guess a T1 is best, but are there other images that would work? Should we write that a T1, or at least that a nifti file, is expected?

2022-03-10 21:37 UTC, CHrlS98 commented on USAGE
> +    --template                                  Template used for registration.
I guess a T1 is best, but are there other images that would work? Should we write that a T1 is expected, or at least that a nifti file is expected?

2022-03-16 13:27 UTC, CHrlS98 approved these changes

2022-03-18 20:55 UTC, mdesco requested changes

2022-03-18 20:55 UTC, mdesco commented on USAGE
> +    --linear                                    If set, it will use linear registration instead of non linear registration.
Please add defaults in ()

2022-03-18 20:55 UTC, mdesco commented on USAGE
> +    --slow_registration                         If set, it will use antsRegistrationSyN instead of antsRegistrationSyNQuick for registration.
add default in ().
Also, please add the slow option as default and rename this option --quick_registration

I think we should always use slow registration unless we are prototyping

2022-03-18 21:06 UTC, mdesco commented on USAGE
> +    --slow_registration                         If set, it will use antsRegistrationSyN instead of antsRegistrationSyNQuick for registration.
Just tested and the --slow_registration option went super fast on Cipaye on 12 subjects. Are you sure that you are truly activating the non-quick version? :)

2022-09-22 18:26 UTC, mdesco approved these changes
Looks good. @CHrlS98 is about to try to it. We can raise issue

2022-10-03 17:14 UTC, CHrlS98 reviewed
Once I fixed the `*` issue (see my comment), it worked perfectly using default parameters. I think it's safe to merge once it is fixed. We'll raise issues if we encounter problems + I'll be able to do PR to fix stuff.

2022-10-03 17:14 UTC, CHrlS98 commented on main.nf
> +    .fromPath("$root/**/t1.nii.gz",
There should be an `*` here before `t1.nii.gz` in order to deal properly with multiple subjects.

2022-10-03 19:25 UTC, CHrlS98 approved these changes
Tried with default options, then with `--quick_registration` and `--linear_registration`. Everything seems to be working perfectly! Ready to merge!

2022-10-03 19:27 UTC, merged